ERROR:root:Unhandled exception: <class 'IndexError'> - list index out of range
NoneType: None
ERROR:root:Traceback (most recent call last):
  File "d:\Tiktok\fMaindb.py", line 572, in addAccounts
    dt[2],
    ~~^^^
IndexError: list index out of range

ERROR:root:Unhandled exception: <class 'IndexError'> - list index out of range
NoneType: None
ERROR:root:Traceback (most recent call last):
  File "d:\Tiktok\fMaindb.py", line 572, in addAccounts
    dt[2],
    ~~^^^
IndexError: list index out of range

ERROR:root:Unhandled exception: <class 'IndexError'> - list index out of range
NoneType: None
ERROR:root:Traceback (most recent call last):
  File "d:\Tiktok\fMaindb.py", line 572, in addAccounts
    dt[2],
    ~~^^^
IndexError: list index out of range

